#include "written.h"
AVXWritten::AVXWrit const *AVXWritten::written[] = {
    AVXWritten::written_01, // placeholder only. So that 
    AVXWritten::written_01,
    AVXWritten::written_02,
    AVXWritten::written_03,
    AVXWritten::written_04,
    AVXWritten::written_05,
    AVXWritten::written_06,
    AVXWritten::written_07,
    AVXWritten::written_08,
    AVXWritten::written_09,

    AVXWritten::written_10,
    AVXWritten::written_11,
    AVXWritten::written_12,
    AVXWritten::written_13,
    AVXWritten::written_14,
    AVXWritten::written_15,
    AVXWritten::written_16,
    AVXWritten::written_17,
    AVXWritten::written_18,
    AVXWritten::written_19,

    AVXWritten::written_20,
    AVXWritten::written_21,
    AVXWritten::written_22,
    AVXWritten::written_23,
    AVXWritten::written_24,
    AVXWritten::written_25,
    AVXWritten::written_26,
    AVXWritten::written_27,
    AVXWritten::written_28,
    AVXWritten::written_29,

    AVXWritten::written_30,
    AVXWritten::written_31,
    AVXWritten::written_32,
    AVXWritten::written_33,
    AVXWritten::written_34,
    AVXWritten::written_35,
    AVXWritten::written_36,
    AVXWritten::written_37,
    AVXWritten::written_38,
    AVXWritten::written_39,

    AVXWritten::written_40,
    AVXWritten::written_41,
    AVXWritten::written_42,
    AVXWritten::written_43,
    AVXWritten::written_44,
    AVXWritten::written_45,
    AVXWritten::written_46,
    AVXWritten::written_47,
    AVXWritten::written_48,
    AVXWritten::written_49,

    AVXWritten::written_50,
    AVXWritten::written_51,
    AVXWritten::written_52,
    AVXWritten::written_53,
    AVXWritten::written_54,
    AVXWritten::written_55,
    AVXWritten::written_56,
    AVXWritten::written_57,
    AVXWritten::written_58,
    AVXWritten::written_59,

    AVXWritten::written_60,
    AVXWritten::written_61,
    AVXWritten::written_62,
    AVXWritten::written_63,
    AVXWritten::written_64,
    AVXWritten::written_65,
    AVXWritten::written_66,
};